import 'package:flutter/material.dart';

List<Color> colors = [
  Colors.green,
  Colors.blue,
  Colors.red,
  Colors.orange,
  Colors.purple,
  Colors.yellow,
  Colors.teal,
  Colors.cyan,
  Colors.indigo,
  Colors.amber,
  Colors.lime,
  Colors.deepOrange,
  Colors.pink,
  Colors.brown,
  Colors.grey,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.deepPurple,
  Colors.blueGrey,
  Colors.blueAccent,
  Colors.orangeAccent,
  Colors.purpleAccent,
  Colors.cyanAccent,
  Colors.limeAccent,
  Colors.yellowAccent,
  Colors.redAccent,
  Colors.greenAccent,
  Colors.pinkAccent,
  Colors.green,
  Colors.blue,
  Colors.red,
  Colors.orange,
  Colors.purple,
  Colors.yellow,
  Colors.teal,
  Colors.cyan,
  Colors.indigo,
];
Color getColor(int index) {
  return colors[index];
}
